### ISSUE TITLE
Restructure similarity data (e.g. store more auxiliary tables permanently) and create version of refresh that can run faster

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/donations#1]
Right now, after any update, refreshing the similarity data refreshes it for the whole database, which is intensive because of the huge number of distinct donors (the time taken increased ten-fold after importing donors from the EA Survey). However, if we store more intermediate tables, then adding data for a specific donor requires only updating all the similarities involving that donor, which should reduce the time taken by a factor of at least 3 and probably 10. We might need to move from executing a SQL file to a stored procedure with parameters so we can pass parameters easily.

**Comment by riceissa** [comment]
See also #10

**Comment by riceissa** [comment]
I think this is basically done now, at https://github.com/vipulnaik/donations/blob/master/similarity/similarity-incremental.sql (for the stored procedure) and https://github.com/vipulnaik/donations/blob/master/similarity/similarity-3.sql (for the version of `similarity-2.sql` that stores more intermedia tables).
