### ISSUE TITLE
Review and fix Arnold Foundation grants processing logic

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/donations#111]
https://github.com/vipulnaik/donations/blob/master/data-update-playbook.md#arnold-foundation

The original location http://www.arnoldfoundation.org/grants/ redirects to https://www.arnoldventures.org/grants/ but that's not the only change -- there also seem to be some data format changes, and in particular I'm getting this error when I do:

```
curl https://www.arnoldventures.org/grants/ > index.html
./fetch_page.py index.html > grants-with-multiyear.tsv
```

Error:

```
Traceback (most recent call last):
  File "./fetch_page.py", line 67, in <module>
    main()
  File "./fetch_page.py", line 16, in main
    area = next(areas)
StopIteration
```

**Comment by riceissa** [comment]
The old website had all of the grants listed in the HTML source: https://web.archive.org/web/20170322234556/http://www.arnoldfoundation.org/grants/

This new website seems to use pagination to split the grants, so it's basically a completely new scraping job.

**Comment by vipulnaik** [comment]
I'd say go ahead and write that new scraping job, if you expect it to take 5 hours or less @riceissa.

**Comment by riceissa** [comment]
I have a basic version of this working now at https://github.com/riceissa/arnold-foundation-grants/blob/master/scrape.py and https://github.com/riceissa/arnold-foundation-grants/blob/master/proc.py

One question I have: The old website groups grants into cause areas so it was possible to track this information, but the new website does not list any cause areas. For the latest grants, we can give up on tracking the cause area (because the info just isn't there), but for grants that were made before this website upgrade, it would be possible to "peek back" at the old data and figure out what the cause area is. Do you want me to do this for these older grants? Or do you just want to give up on cause areas?

**Comment by vipulnaik** [comment]
@riceissa Yes I would like you to backfill the cause area for older grants.

For newer grants, can we fill in the cause area for the most recent older grant to the same org, if any exists?

**Comment by riceissa** [comment]
> Yes I would like you to backfill the cause area for older grants.

Got it.

> For newer grants, can we fill in the cause area for the most recent older grant to the same org, if any exists?

Yes, I can do that.

**Comment by riceissa** [comment]
It looks like Arnold Foundation is doing some kind of weird regrouping of grant amounts. To give an example, in the older grants data there is a grant:

    Education	Charter Fund, Inc.	2016	12000000	multi-year	Grant period: 2016 - 2021

But in the newer grants data, here are all the grants for Charter Fund:

```
"Charter Fund, Inc.","To support the expansion and replication of high-quality schools in New Orleans, Louisiana.",2012 - 2020,"Up To                    $13,586,000"
"Charter Fund, Inc.","To support the expansion and replication of high-quality schools in Camden, New Jersey.",2015 - 2016,"$2,000,000"
"Charter Fund, Inc.","To support the expansion and replication of high-quality schools in Memphis, Tennessee.",2015 - 2018,"$4,500,000"
"Charter Fund, Inc.","To support the expansion and replication of high-quality schools in Camden, New Jersey.",2015 - 2018,"$6,000,000"
"Charter Fund, Inc.","To subsidize the cost of tuition and stipends for first-year Relay Graduate School of Education residents in Camden, New Jersey.",2016 - 2018,"$1,149,000"
"Charter Fund, Inc.",To support continued investments in high-performing charter schools.,2016 - 2019,"$6,000,000"
"Charter Fund, Inc.**","To support the acquisition and improvement of school facilities located in Camden, New Jersey.",2018 - 2022,"$4,100,000"
```

None of them are for $12 million, and also none are 2016-2021.

**Comment by riceissa** [comment]
Besides the issue above, this is now done.

You can generate the SQL file with:

    ./proc.py grants-2019-04-11.csv grants-with-multiyear.tsv

**Comment by riceissa** [comment]
Actually, I forgot to apply the donee and cause area filters, so let me do that.

**Comment by riceissa** [comment]
Ok, this is done.
