### ISSUE TITLE
Write script to read in funding information from gofundme.com/ea-hotel and do currency conversion and enter as donations

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/donations#113]
On the right at https://www.gofundme.com/ea-hotel we see a list of donors with donation amounts in GBP.

I'd like us to be able to read in that webpage and output a SQL file with donation amounts, after the appropriate GBP-to-USD conversion is done,

**Comment by riceissa** [comment]
This is completed at https://github.com/riceissa/gofundme-donations

I've stored the SQL file at https://github.com/riceissa/gofundme-donations/blob/master/ea-hotel.sql

If you want to re-run the scripts, do note that `get_currency_data.py` requires a Fixer.io API key (which you can get for free by signing up for the service).

I've written the scripts with enough generality that it wouldn't be difficult to adapt them to other GoFundMe campaigns, but currently some of the scripts hard-code EA-hotel-specific values (e.g. see [these lines](https://github.com/riceissa/gofundme-donations/blob/b811bf4769e7f946a47812742fa7bd5a0b9bfcc4/proc.py#L34-L40)).

**Comment by vipulnaik** [comment]
Your script does not put commas between the inserted tuples @riceissa 😱

**Comment by riceissa** [comment]
> Your script does not put commas between the inserted tuples @riceissa scream

Thanks for the catch, fixed.
