### ISSUE TITLE
Show amount_original_currency, original_currency, currency_conversion_date and currency_conversion_basis in a formatted sentence along with the printing of donor_amount_reason (if available, otherwise just after notes) in the Notes column for donations

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/donations#134]
This will affect the printing of donations lists for donor pages, donee pages, and donor/donee pages. The file to look at is https://github.com/vipulnaik/donations/blob/master/access-portal/backend/donationNotes.inc

**Comment by riceissa** [comment]
This is now done. I created a PR and it's ready to merge.
