### ISSUE TITLE
Separate out reset and read by table in Makefile

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/donations#138]
Also, the last four lines of `reset` should just be a cal to `reset_cache`.

Targets:

`reset_documents`: drop table documents
`read_documents`: All the stuff in read that involves loading documents
`reset_donations`: drop table donations
`read_donations`: All the stuff in read that involves loading donations
Similarly:

`reset_donees`
`read_donees`
`reset_donors`
`read_donors`
`reset_gifts`
`read_gifts`
`reset_money_moved`
`read_money_moved`
`reset_disclosures`
`read_disclosures`

Alternative idea: maybe have `reset_by_table` and `read_by_table` targets that take  table name as input?

The `reset` and `read` targets should just combine the execution of the relevant targets.

**Comment by riceissa** [comment]
just flagging that this might not work well if some of the tables depend on the others. i think in dlw all of the tables are independent of each other, so this should be fine, but e.g. in aiwatch, the people table depends on the positions and product_creators tables, so the data has to be read in a specific order, so one cannot just pick and choose makefile targets and expect everything to work

https://github.com/riceissa/aiwatch/blob/501620eb3711e8351ed50af8ec1f79ca1c13fb91/sql/people.sql#L94-L103

**Comment by riceissa** [comment]
for the overall target (`reset` and `read`) everything should still work in either case (i _think_ make will respect the orders of the dependencies? or maybe i have to build up the dependencies myself)
