### ISSUE TITLE
Enter donor metadata for donors we have been importing donations for

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/donations#34]
Making a list to help with this:

- [x] Public Welfare Foundation (done by Vipul)
- [x] Pineapple Fund
- [x] MacArthur Foundation
- [x] Machine Intelligence Research Institute (donee; done by Vipul)
- [x] Hewlett Foundation
- [x] Ford Foundation
- [x] Wellcome Trust
- [x] Bauman Foundation
- [x] Unbound Philanthropy
- [x] Templeton Foundation
- [x] Theiss Research
- [x] Michael Dello-Iacovo
- [x] McDowell Foundation
- [x] Nathan Cummings Foundation
- [x] ~Bread & Roses Community Fund~ (this is a wontfix so adding metadata is unnecessary)
- [x] Atlantic Philanthropies
- [x] Foundational Questions Institute
- [x] Knight foundation
- [x] BERI
- [x] Vitalik Buterin
- [x] gwern
- [x] michael dello iacovo
- [x] sloan foundation
- [x] mulago
- [x] google.org (done by vipul)
- [x] Skoll Foundation
- [x] Children's Investment Fund Foundation
- [x] Stone Family Foundation
- [x] Douglas B. Marshall Jr. Family Foundation
- [x] Barr Foundation
- [x] Michael & Susan Dell Foundation
- [x] Chan Zuckerberg Initiative

**Comment by riceissa** [comment]
Making a list to help with this:

- [x] Public Welfare Foundation (done by Vipul)
- [ ] Pineapple Fund
- [ ] MacArthur Foundation
- [x] Machine Intelligence Research Institute (donee; done by Vipul)
- [ ] Hewlett Foundation
- [ ] Ford Foundation
- [ ] Wellcome Trust
- [ ] Bauman Foundation
- [ ] Unbound Philanthropy
- [ ] Templeton Foundation
- [ ] Theiss Research
- [ ] Michael Dello-Iacovo
- [ ] McDowell Foundation
- [ ] Nathan Cummings Foundation
- [ ] Bread & Roses Community Fund
- [ ] Atlantic Philanthropies

**Comment by riceissa** [comment]
I finished adding all the ones for which there are script repos.

**Comment by vipulnaik** [comment]
What about Foundational Questions Institue, per #39 :)?

**Comment by riceissa** [comment]
Added that and BERI to the list.

**Comment by riceissa** [comment]
For donees who are also donors, how does metadata entry work? I am running into this with BERI, which already has metadata entered as a donee but not as a donor.

**Comment by vipulnaik** [comment]
@riceissa I think for such donors you just have to re-enter their data separately in both cases. There may be some data duplication :'(.

**Comment by riceissa** [comment]
got it

**Comment by riceissa** [comment]
Ok I'm done with all the ones listed so far.
