### ISSUE TITLE
Clean up 2017 donor lottery data

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/donations#37]
The most recent version of the data was manually entered as part of https://github.com/vipulnaik/donations/blob/master/sql/donations/donor-lottery.sql
This was well before the lottery was closed to new entries and finalized, so it misses a lot of data and has inaccurate amounts for existing data.

However it is probably better to generate the data programmatically from https://app.effectivealtruism.org/lotteries/31553453298138 and then do a manual or programmatic deduplication step (for donors who have their own donations SQL files, like Ajeya Cotra or Robert Yaman, we will put it in their main file rather than let it stay in the donor lottery page).
 
The block range info can go into the notes column.

**Comment by riceissa** [comment]
The programmatic step is done at https://github.com/riceissa/cea-donor-lottery

You know better about who needs deduplication, so I'll leave that to you.

**Comment by riceissa** [comment]
There was a bug with Adam Gleave, who has multiple blocks (I was only getting block 1 before), which I fixed.

Also the winners were announced: https://app.effectivealtruism.org/lotteries/31553453298138

**Comment by vipulnaik** [comment]
Inserted and verified, closing.
