### ISSUE TITLE
Foundational Questions Institute

### ISSUE THREAD

**Issue by riceissa** [vipulnaik/donations#39]
This is basically done at https://github.com/riceissa/fqxi-grants

I wasn't sure what to do about the cause area, and @vipulnaik might want to change how the notes are arranged. The [SQL file](https://github.com/riceissa/fqxi-grants/blob/master/out.sql) inserts fine.

**Comment by vipulnaik** [comment]
I think that, to keep it consistent with other academic grants, the institution should be the donee,

Also, the URL should be chosen as the URL of the specific grant, not the grants page URL, I think

**Comment by riceissa** [comment]
done

**Comment by vipulnaik** [comment]
Closing for now. Might reopen if I decide to do any specific cleanup
