### ISSUE TITLE
add more donee metadata and documents for BERI

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/donations#41]
https://donations.vipulnaik.com/donee.php?donee=Berkeley+Existential+Risk+Initiative

Augment metadata by linking to timeline, other appropriate fields.

Also add more documents.

**Comment by riceissa** [comment]
Add some metadata.

Doing documents soon.

**Comment by riceissa** [comment]
Added documents in 930bd28a4390e2c26f4ab8f635abbe23c06563e5.
