### ISSUE TITLE
add FLI grants

### ISSUE THREAD

**Issue by riceissa** [vipulnaik/donations#42]

**Comment by riceissa** [comment]
This is now done at https://github.com/riceissa/fli-grants

For the `donee` column I made it the institution rather than primary investigator, which is what we do for Open Philanthropy grants, but let me know if you want something else.

**Comment by riceissa** [comment]
Donation earmark added.

**Comment by vipulnaik** [comment]
Inserted; check out https://donations.vipulnaik.com/donor.php?donor=Future+of+Life+Institute
