### ISSUE TITLE
Consider importing Mulago Foundation grants into DLW

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/donations#46]
http://mulagofoundation.org/who-we-fund

May not be too easy to import the data, because you again have to click on links and then get amounts from the clicked link. But Mulago was highly respected by GiveWell in the early 2010s, so potentially worthwhile.

**Comment by riceissa** [comment]
In progress at https://github.com/riceissa/mulago

**Comment by riceissa** [comment]
There are at least two grantees where the amount has two methods listed:

- [Babban Gona](http://mulagofoundation.org/who-we-fund/babban-gona): "$50K unrestricted grants; $200K loans"
- [Komaza](http://mulagofoundation.org/who-we-fund/komaza): "$550K unrestricted grants, $1 million convertible debt"

Within each grantee, should these amounts be combined into a single donation, or should it be two donations?

**Comment by vipulnaik** [comment]
Let's keep it two donations!

**Comment by riceissa** [comment]
Okay, done! :)

**Comment by vipulnaik** [comment]
Imported!

**Comment by riceissa** [comment]
http://mulagofoundation.org/who-we-fund 404s now.

I think basically the same page is now at http://mulagofoundation.org/portfolio
