### ISSUE TITLE
Look into importing Siegel Family Endowment grants into DLW

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/donations#48]
http://www.siegelendowment.org/ lists grantees but it seems messy. There is also api.siegelendowment.org but not really sure what that is.

If you expect doing this would take more than a day, check with me before proceeding.

**Comment by riceissa** [comment]
The only grantees I see on the site are:

- Featured Grantees (lengthy description, grantee location, grantee website):
  - Data and Society
  - Center on Rural Innovation
  - Peer 2 Peer University
- Selected Grantees (short description, grantee website):
  - New York Hall of Science
  - MIT Press
  - Library For All
  - Wikimedia Foundation
  - Harvard Graduate School of Education
  - Mozilla Science Lab
  - Cooper Hewitt
  - Cornell Tech
  - Citizen Schools
- Additional Grantees (no description, grantee website):
  - Carnegie Hall
  - Coalition for Queens
  - Jobs for the Future
  - Junior Achievement New York
  - Khan Academy
  - MIT Learning Initiative
  - NYC FIRST
  - National Academy Foundation
  - New Profit
  - New Visions for Public Schools
  - New York Public Library
  - Real World Scholars
  - Scratch Foundation
  - Stanford PACS
  - Station1
  - Summit Learning
  - Sunset Spark

When I click on the grantee names, I am taken to the grantee website. I don't see amounts listed anywhere.

**Comment by riceissa** [comment]
https://api.siegelendowment.org/ looks like a WordPress blog, so I don't think it has grants data.

**Comment by riceissa** [comment]
Unless I'm missing something, there doesn't seem to be much on the website. If you just want the grantee names and description (when available -- see above for which ones have a description), that should be a pretty quick manual entry job.

**Comment by vipulnaik** [comment]
We'll close this issue for now, then!
