### ISSUE TITLE
Cover Vitalik Buterin's donations and documents

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/donations#50]
Currently, only his donation to MIRI is included, based on MIRI's own data on top donors: https://donations.vipulnaik.com/donor.php?donor=Vitalik+Buterin

However, he has made other big donations, such as $2.4 million to SENS Research Foundation: https://www.leafscience.org/vitalik-buterin-the-best-thing-to-donate-money-to-is-the-fight-against-aging/

He has also spoken about donations and altruism (e.g. above link) so we can also get some document rows for him.

**Comment by riceissa** [comment]
See the following commits:

- 5aa491d11fd617b657465126a06f0d3354bc6046
- 64f5918e42a85ab76ea9fdcd00b9704d4b6baa84
- 11c95b3722f4eb000fdaf554509c8b2376d11d44

**Comment by vipulnaik** [comment]
Will reinsert everything along with the fixed-up data for #49.
