### ISSUE TITLE
gwern donations

### ISSUE THREAD

**Issue by riceissa** [vipulnaik/donations#51]
https://twitter.com/gwern/status/667082325637914625

I think he has mentioned at least one other donation (on reddit?)

**Comment by riceissa** [comment]
There is also the $20 donation to Danbooru, but I'm not sure if you want to cover that since it involves an account upgrade. https://www.gwern.net/Danbooru2017#scraping

**Comment by riceissa** [comment]
I had to edit the `donations` table schema to add Coindesk to `currency_conversion_basis` for converting one bitcoin donation, so you will have to reload the schema to insert gwern's donations.

**Comment by vipulnaik** [comment]
Will reinsert everything along with the completely fixed-up data for #49.

**Comment by riceissa** [comment]
I did end up adding the Danbooru one, in 23755e68b7921190f541999cef03a0056071a6d5
