### ISSUE TITLE
Create playbook to systematically update as much grants data as possible for DLW, that can be used periodically

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/donations#52]
The playbook would mostly be a sequence of commands to run, and manual checks to perform and review (so it cannot be end-to-end automated, but it can be scripted with a mix of computers and humans executing the script).

The goal is to make sure that donation data for all the major foundations and significant individual donors are updated. We could end up with a few different playbooks, one for the foundations (that Issa could execute) and one for individual donors (that Vipul could execute).

**Comment by riceissa** [comment]
Example of what a "playbook" might look like (for a different project): https://github.com/riceissa/timelines-wiki-main-page-table/blob/master/README.md

**Comment by riceissa** [comment]
I've started on this at https://github.com/vipulnaik/donations/blob/master/data-update-playbook.md

**Comment by riceissa** [comment]
I think this is pretty much done.

The only thing that's partway done is individual donors. I started doing these, but the instructions were all very short and boiled down to (1) run `select distinct(url) from donations where donor='NAME';` to see where the current data is coming from; (2) go back to those URLs and get new data. So I stopped.

What are your thoughts?
