### ISSUE TITLE
Import Stone Family Foundation grants data into DLW

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/donations#55]
They do not appear to have a central listing of grants, but each of these pages lists the grantees in that specific part of their work. If you click the links to the individual grantees you'll get the grant amount and period.

http://www.thesff.com/water-and-sanitation/enterprises-in-safe-water/
http://www.thesff.com/water-and-sanitation/urban-sanitation-services/
http://www.thesff.com/water-and-sanitation/waste-to-resource/
http://www.thesff.com/water-and-sanitation/rural-sanitation-in-cambodia/
http://www.thesff.com/mental-health/
http://www.thesff.com/disadvantaged-youth/

**Comment by riceissa** [comment]
This is now done at https://github.com/riceissa/stone-family-foundation

**Comment by vipulnaik** [comment]
I forgot to close this after importing it, closing now.
