### ISSUE TITLE
Import Michael and Susan Dell Foundation grants data into DLW

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/donations#58]
https://www.msdf.org/funding/

**Comment by riceissa** [comment]
The page says "The grants listed below represent grants that were active during the last 12 months" so it doesn't look like this is all of the grants.

**Comment by riceissa** [comment]
It looks like the foundation used to have a "master grant list" https://web.archive.org/web/20121125042102/http://www.msdf.org:80/grants/master-grant-list/

The list doesn't work in the archived versions.

**Comment by riceissa** [comment]
Some even older versions of the website have more grants listed: https://web.archive.org/web/20061112105918/http://www.msdf.org:80/priorities/Priorities.aspx?id=2

**Comment by riceissa** [comment]
https://web.archive.org/web/20061112105147/http://www.msdf.org:80/priorities/MasterList.aspx

**Comment by riceissa** [comment]
Looks like this is the last snapshot of the master grants list that shows all the grants: https://web.archive.org/web/20080224064534/http://www.msdf.org:80/priorities/MasterList.aspx

**Comment by riceissa** [comment]
Ok this is now done at https://github.com/riceissa/dell-foundation

`out.sql` contains both the present-day grants (from the link you gave in OP) plus the grants in the 2008-02-24 master list.

**Comment by vipulnaik** [comment]
Inserted data, need to next figure out the way to handle cause areas.
