### ISSUE TITLE
Import Future Justice Fund grants data into DLW

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/donations#59]
Grantees are listed in the focus area pages. Grant amounts do not appear to be listed:
https://www.futurejusticefund.org/criminaljustice
https://www.futurejusticefund.org/incomesecurity

This is the fund of Mike Krieger and Kaitlyn Trigger, who partnered briefly with the Open Philanthropy Project but then chose to branch off and focus on criminal justice reform. Their criminal justice grants are influenced by Chloe Cockburn, Open Phil's criminal justice program officer, per https://www.openphilanthropy.org/blog/update-partnerships-external-donors, so list her as `influencer` for those.

Also related reading: https://www.insidephilanthropy.com/home/2016/6/10/safer-stronger-communities-a-young-tech-couple-embraces-crim.html

**Comment by riceissa** [comment]
This is done at https://github.com/riceissa/future-justice-fund

**Comment by vipulnaik** [comment]
Done importing; closing.
