### ISSUE TITLE
Add section on influencer pages listing all donations influenced by them

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/donations#65]
For instance, https://donations.vipulnaik.com/influencer.php?influencer=GiveWell should have a list of all donations that list GiveWell as the influencer (or, to take into account donations with multiple influencers, all donations where GiveWell is one of the influencers).

The format can be the same as the donation lists we see on the donor and donee pages, except that we need to include a column for the donor and for the donee, and omit the column for the influencer.

https://donations.vipulnaik.com/donor.php?donor=Open+Philanthropy+Project#donorDonationList

https://donations.vipulnaik.com/donee.php?donee=LessWrong+2.0#doneeDonationList

https://github.com/vipulnaik/donations/blob/master/access-portal/backend/donorDonationList.inc

https://github.com/vipulnaik/donations/blob/master/access-portal/backend/doneeDonationList.inc

**Comment by riceissa** [comment]
Ok, I think this is working.

**Comment by vipulnaik** [comment]
Verified this is working, closing.
