### ISSUE TITLE
Import Knut and Alice Wallenberg Foundation grants into DLW

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/donations#68]
https://kaw.wallenberg.org/en/grants

**Comment by riceissa** [comment]
I will be working on this at https://github.com/riceissa/kaw-wallenberg-foundation

**Comment by riceissa** [comment]
Ok, I did some manual checks of the data (and fixed some things).

The only issue now is the thing I mentioned in chat, where one of the grants is 10 times larger than the endowment of the foundation.

* Grant:
  * "Wallenberg Centre for Protein Research, WCPR, SEK 340 billion during 2016-2023" https://kaw.wallenberg.org/en/strategic-grants
* Endowment:
  * "SEK m 39,035 (2012)" https://en.wikipedia.org/wiki/Knut_and_Alice_Wallenberg_Foundation
  * "kr 32.7 billion (SEK)" https://en.wikipedia.org/wiki/List_of_wealthiest_charitable_foundations

So maybe the grants page meant SEK 340 million.

**Comment by riceissa** [comment]
I emailed them.

**Comment by riceissa** [comment]
They didn't reply to me, but the page now says "340 million".

**Comment by riceissa** [comment]
Ok, I've regenerated the SQL file using the new grant amount.
