### ISSUE TITLE
Add sections for influencer donation amounts by donor and year, donee and year

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/donations#69]
On the influencer page, add sections for "Influencer donation amounts by donor and year" and "Influencer donation amounts by donee and year" similar to:

https://donations.vipulnaik.com/donor.php?donor=Open+Philanthropy+Project#donorDonationAmountsByDoneeAndYear

Source: https://github.com/vipulnaik/donations/blob/master/access-portal/backend/donorDonationAmountsByDoneeAndYear.inc

**Comment by riceissa** [comment]
I think this is working.
