### ISSUE TITLE
Import Hewlett Foundation grants data into Donations List Website

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/donations#7]
See https://www.hewlett.org/grants/

Data is also available via IATI, and we've previously created summary tables of the IATI data for use on Wikipedia.

**Comment by riceissa** [comment]
Tables on Wikipedia: https://en.wikipedia.org/wiki/Hewlett_Foundation#International_grants_tables

The source seems to be in a secret gist.

**Comment by riceissa** [comment]
"The majority of Hewlett’s grantmaking is domestically focused on programs in the United States. The IATI data will cover approximately 21% of Hewlett’s overall grantmaking." https://www.iatiregistry.org/publisher/about/hewlett-foundation

https://www.hewlett.org/iati/

**Comment by riceissa** [comment]
This is now in progress at https://github.com/riceissa/hewlett-foundation

**Comment by riceissa** [comment]
hewlett is done (i.e. same status as the other ones, where we need to map stuff/decide where some stuff goes)

(I had announced this in chat but also announcing it here)

**Comment by vipulnaik** [comment]
Inserted. We may tweak the cause areas a bit later, but closing for now.

And wow, they are the second biggest all-time donor after BMGF now :).
