### ISSUE TITLE
Choose canonicalization between "University of Oxford" and "Oxford University" and transform everything accordingly

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/donations#81]
https://donations.vipulnaik.com/donee.php?donee=Oxford+University
https://donations.vipulnaik.com/donee.php?donee=University+of+Oxford

The former has metadata entered (but it links to a Wikipedia page using the latter), and both formats show up for many donors.

Similarly for Cambridge:

https://donations.vipulnaik.com/donee.php?donee=Cambridge+University
https://donations.vipulnaik.com/donee.php?donee=University+of+Cambridge

**Comment by riceissa** [comment]
I'm wondering if it's best to create a `dlw_common` repo like https://github.com/riceissa/devec_sql_common that includes a "master donor/donee map" that canonicalizes all the names.
