### ISSUE TITLE
Add in details of 2018 donor lottery once they are finalized (maybe after the draw date of January 30, 2019)

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/donations#85]
These are the two lotteries:

- $100K lottery: https://app.effectivealtruism.org/lotteries/63715163508812
- $500K lottery: https://app.effectivealtruism.org/lotteries/63715163508813

I think there's no point adding details now, because a lot of details are still pending finalization.

**Comment by riceissa** [comment]
I've made adjustments to the processing script and added the new data, so this should now work using the instructions at https://github.com/riceissa/cea-donor-lottery#running-the-processing-script

There's at least one donation that is tracked elsewhere (namely, your $500 entry). The easiest thing to do would be to edit the HTML files (e.g. `data-january-2019-500k.html`) to remove these entries, or to edit the output SQL file to remove the corresponding rows, but I would need to have a list of all such donations.
