### ISSUE TITLE
Arch Community Fund donations

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/donations#87]
Website: http://www.archcommunityfund.org/grantees.html

Each set of grants seems to be announced in a blog post; all grants seem to be $25,000 at least for the first round.

http://www.archcommunityfund.org/grantee/2018/05/16/test-grantee.html

**Comment by riceissa** [comment]
> Each set of grants seems to be announced in a blog post

I only see one blog post (not that you said otherwise, but "each set" is strange to say when there is only one set).
