### ISSUE TITLE
Add donee metadata for these specified donees

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/donations#88]
Might overlap somewhat with #77.

Donee list:

- [x] EA Hotel: https://eahotel.org/ https://donations.vipulnaik.com/donee.php?donee=EA+Hotel
- [x] Global Catastrophic Risk Institute: https://donations.vipulnaik.com/donee.php?donee=Global+Catastrophic+Risk+Institute
- [x] Global Priorities Institute: https://donations.vipulnaik.com/donee.php?donee=Global+Priorities+Institute
- [x] Forethought Foundation for Global Priorities Research: https://donations.vipulnaik.com/donee.php?donee=Forethought+Foundation+for+Global+Priorities+Research
- [x] Utility Farm: https://donations.vipulnaik.com/donee.php?donee=Utility+Farm
- [x] Rethink Priorities: https://donations.vipulnaik.com/donee.php?donee=Rethink+Priorities

**Comment by riceissa** [comment]
This is done and ready for you to review.
