### ISSUE TITLE
Add Sandler Foundation grants

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/donations#89]
See https://www.sandlerfoundation.org/grants/

Unfortunately no grant date or amount is available.

For a simple first pass we can just put a grant date of 2019; we've already dealt with unknown amounts by setting them to null. In the notes, note that the grant dates are unknown because they don't provide individual grant data.

You can leave the cause area blank since it doesn't appear that the Sandler Foundation includes any cause area information.

**Comment by riceissa** [comment]
This is done; all that's left is for you to review it.

**Comment by vipulnaik** [comment]
inserted; closing
