### ISSUE TITLE
Add grants for the Haas, Jr. Fund

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/donations#92]
https://www.haasjr.org/grants/search
Also add donor metadata and update data update playbook

**Comment by riceissa** [comment]
Grants data collection and processing is done and can be found at <https://github.com/riceissa/haasjr-fund>. I already ran `scrape.py` and stored the result at `data-2019-01-19.csv` so you will just need to run `proc.py`.

I also updated the playbook.

**Comment by riceissa** [comment]
added donor metadata
