### ISSUE TITLE
Add grants for Andrea & Charles Bronfman Philanthropies

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/donations#95]
http://www.acbp.net/grant-directory.php

It doesn't look like grant amounts are included, but the note on top indicates that all grantees received at least one grant of at least $10,000.

We can just insert them all with $10,000 each, for 2016 as the year (which seems to be their last year they have said anything about).

Also add donor metadata and update data update playbook.

**Comment by riceissa** [comment]
This is completed at https://github.com/riceissa/andrea-and-charles-bronfman-philanthropies

I've already downloaded the data into `data-2019-04-23.csv` so you can just run `proc.py`.
