### ISSUE TITLE
Add grants from the John Merck Fund

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/donations#96]
https://www.jmfund.org/program-grants/

Also update data update playbook and add donor metadata.

**Comment by riceissa** [comment]
There are several $0 donations https://www.jmfund.org/program-grants/?fwp_grant_amounts=0.00%2C0.00

**Comment by riceissa** [comment]
This is now completed at https://github.com/riceissa/john-merck-fund

I already downloaded the data into `data-2019-04-23.csv` so you can just run `proc.py`.
