### ISSUE TITLE
Add grants from the Robert Bowne Foundation

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/donations#99]
https://www.robertbownefoundation.org/grants.php (note that there is an year selection that can be switched)

Also add donor metadata and update data update playbook.

**Comment by riceissa** [comment]
For 2007, the page says "In 2007 The Robert Bowne Foundation disbursed $960,000 in grants" but when I add up the grants on the page I get $935,000. Manually adding up the section totals, I also get 145000 + 705000 + 75000 + 10000 = 935000.

For all the other years I get the same amount as the claimed total.

**Comment by riceissa** [comment]
The grants data part is completed at https://github.com/riceissa/robert-bowne-foundation

I already downloaded the grants data into `grants.csv` so you should just be able to run:

    ./proc.py grants.csv > out.sql
